name: biome_on_pull_request

on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Biome'
      run: npm install biome
    - name: 'run Biome'
      run: npm run biome:ci